<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Framework\App\Action\Action;

?>
<?php
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$callForPriceObj = $block->getLayout()->createBlock(Adorncommerce\CallForPrice\Block\CallForPrice::class);
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper(Magento\Catalog\Helper\Output::class);
$helper = $block->getData('viewModel')->getHelperData()
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty">
        <div><?= $block->escapeHtml(__('We can\'t find products matching the selection.')) ?></div>
    </div>
<?php else: ?>
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $imageDisplayArea = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $imageDisplayArea = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?= /* @noEscape */
    $viewMode ?> products-<?= /* @noEscape */
    $viewMode ?>">
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
                <li class="item product product-item">
                    <div class="product-item-info" data-container="product-<?= /* @noEscape */
                    $viewMode ?>">
                        <?php
                        $productImage = $block->getImage($_product, $imageDisplayArea);
                        if ($pos != null) {
                            $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                . 'top:' . $productImage->getHeight() . 'px;"';
                        }
                        ?>
                        <?php // Product Image ?>
                        <a href="<?= $block->escapeUrl($_product->getProductUrl()) ?>"
                           class="product photo product-item-photo"
                           tabindex="-1">
                            <?= $productImage->toHtml() ?>
                        </a>
                        <div class="product details product-item-details">
                            <?php
                            $_productNameStripped = $block->
                            stripTags($_product->getName(), null, true);
                            ?>
                            <strong class="product name product-item-name">
                                <a class="product-item-link"
                                   href="<?= $block->escapeUrl($_product->getProductUrl()) ?>">
                                    <?= /* @noEscape */
                                    $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                                </a>
                            </strong>
                            <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
                            <?php if ($_product->isSaleable() &&
                                !$helper->isEnable($_product->getData('call_for_price_active')) &&
                                (($helper->isEnableForZeroPrice() == 0) ||
                                    ($_product->getPrice() != 0))): ?>
                                <?= /* @noEscape */ $block->getProductPrice($_product) ?>
                            <?php endif; ?>
                            <?= $block->getProductDetailsHtml($_product) ?>
                            <div class="product-item-inner">
                                <div
                                    class="product actions product-item-actions"
                                    <?= strpos($pos, $viewMode . '-actions')
                                        ? $block->escapeHtmlAttr($position) : '' ?>>
                                    <div
                                        class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ?
                                        $block->escapeHtmlAttr($position) : '' ?>>
                                        <?php if ($_product->isSaleable() &&
                                            !$helper->isEnable($_product->getData('call_for_price_active')) &&
                                            (($helper->isEnableForZeroPrice() == 0) || (($_product->getPrice()) != 0) ||
                                                ($_product->getTypeId() == 'configurable'))): ?><?php $postParams =
                                            $block->getAddToCartPostParams($_product); ?>
                                            <form data-role="tocart-form"
                                                  data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>"
                                                  action="<?= $block->escapeUrl($postParams['action']) ?>"
                                                  method="post">
                                                <input type="hidden"
                                                       name="product"
                                                       value="<?= /* @noEscape */
                                                        $postParams['data']['product'] ?>">
                                                <input type="hidden" name="<?= /* @noEscape */
                                                Action::PARAM_NAME_URL_ENCODED ?>"
                                                       value="<?= /* @noEscape */
                                                        $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                                   <?= $block->getBlockHtml('formkey') ?>
                                                <button type="submit"
                                                        title="<?= $block->escapeHtmlAttr(__('Add To Cart')) ?>"
                                                        class="action tocart primary">
                                                    <span><?= $block->escapeHtml(__('Add To Cart')) ?></span>
                                                </button>
                                            </form>
                                        <?php elseif ($helper->isEnable(
                                            $_product->getData('call_for_price_active')
                                        ) ||
                                                          (($helper->isEnableForZeroPrice() == 1) &&
                                                          (($_product->getPrice()) == 0)) ||
                                                          ($_product->getTypeId() != 'configurable')): ?>
                                                              <?php $buttontext = $helper->getButtonText(); ?>
                                            <a href="javascript:void(0)" target="_self"
                                               id="buttoncallforprice<?= /* @noEscape */ $_product->getId() ?>"
                                               class="action primary tocart callfor-price">
                                                <span><?= /* @noEscape */ $buttontext; ?></span></a>
                                        <?php else: ?>
                                            <?php if ($_product->isAvailable()): ?>
                                                <div class="stock available">
                                                    <span><?= $block->escapeHtml(__('In stock')) ?></span></div>
                                            <?php else: ?>
                                                <div class="stock unavailable">
                                                    <span><?= $block->escapeHtml(__('Out of stock')) ?></span>
                                                </div>
                                            <?php endif; ?>
                                        <?php endif; ?>
                                    </div>
                                    <div data-role="add-to-links"
                                         class="actions-secondary"<?= strpos($pos, $viewMode . '-secondary') ?
                                            $block->escapeHtmlAttr($position) : '' ?>>
                                        <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                            <?= $addToBlock->setProduct($_product)->getChildHtml() ?>
                                        <?php endif; ?>
                                    </div>
                                </div>
                                <?php if ($showDescription): ?>
                                    <div class="product description product-item-description">
                                        <?= /* @noEscape */
                                        $_helper->productAttribute(
                                            $_product,
                                            $_product->getShortDescription(),
                                            'short_description'
                                        ) ?>
                                        <a href="<?= $block->escapeUrl($_product->getProductUrl()) ?>"
                                           title="<?= /* @noEscape */
                                            $_productNameStripped ?>"
                                           class="action more"><?= $block->escapeHtml(__('Learn More')) ?></a>
                                    </div>
                                <?php endif; ?>
                            </div>
                        </div>
                    </div>
                </li>
                <?php endforeach; ?>
            <?php foreach ($_productCollection as $_product): ?>
                <?php
                if ($helper->isAvailableForCustomer()):
                    ?>
                <div id="list-call-for-price-form<?= /* @noEscape */ $_product->getId() ?>"
                     class="no-display quick-popup-qquote"
                     style="display: none">
                    <?php
                    $customerData = false;
                    if ($callForPriceObj->getCustomerData()) {
                        $customerData = $callForPriceObj->getCustomerData();
                    }
                    ?>
                    <form method='post' class="formquickquote form-create-account" data-mage-init='{"validation":{}}'
                          id="callforpricePopup" name="callforpricePopup"
                          action='<?=/* @noEscape */$this->getUrl('callforprice/index/submit', ['_secure' => true]) ?>'>
                        <div class="formquickquote-form">
                            <div class="fieldset">
                                <?php if ($customerData):
                                    $email = $customerData->getData('email') ? $customerData->getData('email')
                                        : $block->getCustomerEmail();
                                    endif; ?>
                                <input type='text'
                                           <?php if ($customerData): ?>
                                               value="<?= /*@noEscaped*/ $customerData->getName() ?>"
                                    <?php endif; ?>
                                       name='customer[name]' class="required-entry input-text"
                                       placeholder="<?= 'Name' ?> *"/>
                            </div>
                            <div class="fieldset">
                                <input <?php if (!empty($email)): ?>readonly="readonly"<?php endif; ?>
                                       type='email' <?php if ($customerData): ?> value="<?= /*@noEscaped*/ $email; ?>"
                                <?php endif; ?>
                                       name='customer[email]' class="input-text required-entry validate-email"
                                       placeholder="<?= 'Email Address' ?> *"/>
                            </div>
                            <div class="fieldset">
                                <input type='text' value="" name='customer[telephone]'
                                       data-validate="{'validate-number':true}"
                                       class="input-text required-entry" placeholder="<?= 'Telephone' ?> *"/>
                            </div>

                            <div class="fieldset">
                                <input type='number' value="" name='customer[product_qty]'
                                       data-validate="{'validate-number':true}"
                                       class="input-text required-entry"
                                       placeholder="<?= 'Quantity Needed' ?> *"/>
                            </div>
                            <div class="fieldset">
                    <textarea id="customer[request_details]" class="input-text"
                              name="customer[request_details]"
                              placeholder="<?= 'Comment' ?>"></textarea>
                            </div>
                            <div class="fieldset">
                                <button id="formcallforpricesubmit" type="submit" class="action primary"
                                        title="<?= 'Request Call For Price' ?>">
                                    <span><span><?= 'Request Call For Price' ?></span></span></button>
                            </div>
                            <input type="hidden" name="product_id" value="<?php if ($_product) {
                                /*@noEscaped*/ echo $_product->getId();
                                                                          } ?>"/>

                            <input type="hidden" name="customer_id" value="<?php if ($customerData) {
                                /*@noEscaped*/ echo $customerData->getId();
                                                                           } ?>"/>
                            <input type="hidden" name="product_name" value="<?php if ($_product) {
                                /*@noEscaped*/ echo $_product->getName();
                                                                            } ?>"/>
                            <p>
                                <?= 'Note: Please include as much details and relevant options about the
                                item to help us match your request with an accurate price.' ?>
                            </p>
                        </div>
                    </form>
                </div>
                <script>
                    require(
                        [
                            'jquery',
                            'Magento_Ui/js/modal/modal'
                        ],
                        function (
                            $,
                            modal
                        ) {
                            $(document).ready(function () {
                                var options = {
                                    type: 'popup',
                                    responsive: true,
                                    innerScroll: true,
                                    title: 'Call For Price for <?php if ($_product) {
                                        /* @noEscape */ echo $_product->getName();
                                                               } ?>',
                                    opened: function () {
                                        jQuery(".modal-footer").hide();
                                    },
                                    closeDialog: function () {
                                        this.modal.modal('closeModal');
                                        this.modal = null;
                                    }
                                };
                                var popup = modal(options, $('#list-call-for-price-form' +
                                    <?= /* @noEscape */ $_product->getId()?>));
                                $("#buttoncallforprice" +<?= /* @noEscape */ $_product->getId()?>)
                                    .on('click', function () {
                                    $('#list-call-for-price-form' +<?= /* @noEscape */ $_product->getId()?>)
                                        .modal("openModal");
                                });
                            });
                        });
                </script>
                <?php endif; ?>
            <?php endforeach; ?>
        </ol>
    </div>
    <?= $block->getChildBlock('toolbar')->setIsBottom(true)->toHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()): ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= $block->escapeJs($_product->getSku()) ?>"
                }
            }
        }

        </script>
    <?php endif; ?>
<?php endif; ?>

