<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $helper = $block->getData('viewModel')->getHelperData()?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php $callForPrice = $_product->getCallForPriceActive(); ?>
<?php if ($_product->isSaleable()): ?>
    <div class="box-tocart">
        <div class="fieldset">
            <?php if ($block->shouldRenderQuantity()): ?>
                <div class="field qty">
                    <label class="label" for="qty"><span><?= $block->escapeHtml(__('Qty')) ?></span></label>
                    <div class="control">
                        <input type="number"
                               name="qty"
                               id="qty"
                               min="0"
                               value="<?= $block->getProductDefaultQty() * 1 ?>"
                               title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                               class="input-text qty"
                               data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                        />
                    </div>
                </div>
            <?php endif; ?>
            <div class="actions">
                <?php if ($_product->isSaleable() && !$helper->isEnable($_product->getData('call_for_price_active'))
                    && (($helper->isEnableForZeroPrice()==0) || (($_product->getPrice()) != 0) ||
                        ($_product->getTypeId() == 'configurable') )): ?>
                    <!-- Cart button start -->
                    <button type="submit"
                            title="<?= $block->escapeHtmlAttr($buttonTitle) ?>"
                            class="action primary tocart"
                            id="product-addtocart-button" disabled>
                        <span><?= $block->escapeHtml($buttonTitle) ?></span>
                    </button>
                    <!-- Cart button stop -->
                <?php else: ?>
                    <?php $buttontext = $helper->getButtonText(); ?>
                    <a href="javascript:void(0)" id="call-for-price" target="_self"
                       style="text-align: center;"
                       class="action primary tocart callfor-price"><span><?= /*@noEscaped*/ $buttontext; ?></span></a>
                <?php endif; ?>
                <?= $block->getChildHtml('', true) ?>
            </div>
        </div>
    </div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }

</script>
