<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
// phpcs:disable PSR2.ControlStructures.SwitchDeclaration
// phpcs:disable Generic.WhiteSpace.ScopeIndent

/* @var $block \Magento\Catalog\Block\Product\Compare\ListCompare */
?>
<?php $callForPriceObj = $block->getLayout()->createBlock(Adorncommerce\CallForPrice\Block\CallForPrice::class);
$_productCollection = $block->getLoadedProductCollection(); ?>
<?php $total = $block->getItems()->getSize() ?>
<?php $_helper = $block->getData('viewModel')->getHelperData()?>
<?php if ($total):?>
    <a href="#" class="action print hidden-print" title="<?= $block->escapeHtmlAttr(__('Print This Page')) ?>">
        <span><?= $block->escapeHtml(__('Print This Page')) ?></span>
    </a>
        <div class="table-wrapper comparison">
            <table class="data table table-comparison" id="product-comparison"
                data-mage-init='{"compareList":{
                    "windowPrintSelector":".action.print",
                    "productsInRow":"5",
                    "selectors":{
                        "productAddToCartSelector":"button.action.tocart"}
                }}'>
                <caption class="table-caption"><?= $block->escapeHtml(__('Compare Products')) ?></caption>
                <thead>
                <tr>
                    <?php $index = 0 ?>
                    <?php foreach ($block->getItems() as $item):?>
                        <?php if ($index++ == 0):?>
                            <th scope="row" class="cell label remove"><span>
                                    <?= /* @noEscape */$block->escapeHtml(__('Remove Product')) ?></span></th>
                        <?php endif; ?>
                        <td class="cell remove product hidden-print">
                            <?php $compareHelper = $this->helper(Magento\Catalog\Helper\Product\Compare::class);?>
                            <a href="#" data-post='<?= /* @noEscape */ $compareHelper->getPostDataRemove($item) ?>'
                               class="action delete" title="<?= $block->escapeHtmlAttr(__('Remove Product')) ?>">
                                <span><?= $block->escapeHtml(__('Remove Product')) ?></span>
                            </a>
                        </td>
                    <?php endforeach; ?>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <?php $index = 0; ?>
                    <?php $helper = $this->helper(Magento\Catalog\Helper\Output::class); ?>
                    <?php /** @var $item \Magento\Catalog\Model\Product */ ?>
                    <?php foreach ($block->getItems() as $item):?>
                        <?php if ($index++ == 0):?>
                            <th scope="row" class="cell label product">
                                <span><?= $block->escapeHtml(__('Product')) ?></span>
                            </th>
                        <?php endif; ?>
                        <td data-th="<?= $block->escapeHtmlAttr(__('Product')) ?>" class="cell product info">
                            <a class="product-item-photo"
                               href="<?= $block->escapeUrl($block->getProductUrl($item)) ?>"
                               title="<?= /* @noEscape */ $block->stripTags(
                                   $item->getName(),
                                   null,
                                   true
                               ) ?>">
                                <?= $block->getImage($item, 'product_comparison_list')->toHtml() ?>
                            </a>
                            <strong class="product-item-name">
                                <a href="<?= $block->escapeUrl($block->getProductUrl($item)) ?>"
                                   title="<?= /* @noEscape */ $block->stripTags(
                                       $item->getName(),
                                       null,
                                       true
                                   ) ?>">
                                    <?= /* @noEscape */ $helper->productAttribute($item, $item->getName(), 'name') ?>
                                </a>
                            </strong>
                            <?= $block->getReviewsSummaryHtml($item, 'short') ?>
                            <?php if ($item->isSaleable() && !$_helper->isEnable(
                                $item->getData('call_for_price_active')
                            ) && (($_helper->isEnableForZeroPrice()==0)
                                    || ($item->getPrice()!=0) || ($item->getTypeId() == 'configurable'))): ?>
                            <?= /* @escapeNotVerified @noEscape*/ $block->getProductPrice($item, '-compare-list-top') ?>
                            <?php endif; ?>
                            <div class="product-item-actions hidden-print">
                                <div class="actions-primary">
                                    <?php if ($item->isSaleable() && !$_helper->isEnable(
                                        $item->getData('call_for_price_active')
                                    ) &&
                                        (($_helper->isEnableForZeroPrice()==0) ||
                                            (($item->getPrice()) != 0) ||
                                            ($item->getTypeId() == 'configurable'))): ?>
                                        <form data-role="tocart-form" action="<?= /* @escapeNotVerified @noEscape*/
$this->helper(\Magento\Catalog\Helper\Product\Compare::class)->getAddToCartUrl($item) ?>" method="post">
                                            <?= $block->getBlockHtml('formkey') ?>
                                            <button type="submit" class="action tocart primary">
                                                <span><?= /* @escapeNotVerified @noEscape*/ __('Add to Cart') ?></span>
                                            </button>
                                        </form>
                                    <?php elseif ($_helper->isEnable($item->getData('call_for_price_active'))
                                        || (($_helper->isEnableForZeroPrice()==1) && (($item->getPrice()) == 0)
                                            || ($item->getTypeId() != 'configurable'))): ?>
                                        <?php  $buttontext = $_helper->getButtonText(); ?>
                                        <a href="javascript:void(0)"
                                           target="_self" id="buttoncallforprice<?= /* @noEscape */$item->getId() ?>"
                                           class="action primary tocart callfor-price"><span><?=/* @noEscape */
$buttontext; ?></span>
                                        </a>
                                    <?php else: ?>
                                        <?php if ($item->getIsSalable()): ?>
                                            <div class="stock available"><span><?= /* @escapeNotVerified @noEscape*/
__('In stock') ?></span></div>
                                        <?php else: ?>
                                            <div class="stock unavailable"><span><?= /* @escapeNotVerified @noEscape*/
__('Out of stock') ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                                <?php if ($this->helper(\Magento\Wishlist\Helper\Data::class)->isAllow()): ?>
                                    <div class="secondary-addto-links actions-secondary" data-role="add-to-links">
                                        <a href="#" data-post='<?= /* @escapeNotVerified @noEscape*/
$block->getAddToWishlistParams($item) ?>' class="action towishlist" data-action="add-to-wishlist">
                                            <span><?= /* @escapeNotVerified @noEscape*/ __('Add to Wish List') ?></span>
                                        </a>
                                    </div>
                                <?php endif; ?>
                            </div>
                        </td>
                    <?php
                    if ($_helper->isAvailableForCustomer()):
                            ?>
                        <div id="list-call-for-price-form<?= /* @noEscape*/ $item->getId() ?>"
                             class="no-display quick-popup-qquote"
                             style="display: none">
                            <?php
                            $customerData = false;
                            if ($callForPriceObj->getCustomerData()) {
                                $customerData = $callForPriceObj->getCustomerData();
                                }
                            ?>
                            <form method='post' class="formquickquote form-create-account"
                                  data-mage-init='{"validation":{}}'
                                  id="callforpricePopup" name="callforpricePopup"
                                  action='<?= /*@noEscape */$this->getUrl('callforprice/index/submit', ['_secure' =>
                                      true]) ?>'
                            >
                                <div class="formquickquote-form">
                                    <div class="fieldset">
                                        <?php if ($customerData):
                                            $email = $customerData->getData('email') ?
                                                $customerData->getData('email') : $block->getCustomerEmail();
                                            endif; ?>
                                        <input type='text'
                                                       <?php if ($customerData): ?>value="<?= /* @noEscape */
$customerData->getName()
                                                       ?>"<?php endif; ?>
                                               name='customer[name]' class="required-entry input-text"
                                               placeholder="<?= 'Name' ?> *"/>
                                    </div>
                                    <div class="fieldset">
                                        <input <?php if (!empty($email)): ?>readonly="readonly"<?php endif; ?>
                                               type='email' <?php if ($customerData): ?> value="<?= /* @noEscape */
$email; ?>"
                                                        <?php endif; ?>
                                               name='customer[email]' class="input-text required-entry validate-email"
                                               placeholder="<?= 'Email Address' ?> *"/>
                                    </div>
                                    <div class="fieldset">
                                        <input type='text' value="" name='customer[telephone]'
                                               data-validate="{'validate-number':true}"
                                               class="input-text required-entry" placeholder="<?= 'Telephone' ?>
                                               *"/>
                                    </div>

                                    <div class="fieldset">
                                        <input type='number' value="" name='customer[product_qty]'
                                               data-validate="{'validate-number':true}"
                                               class="input-text required-entry"
                                               placeholder="<?= 'Quantity Needed' ?> *"/>
                                    </div>
                                    <div class="fieldset">
                    <textarea id="customer[request_details]" class="input-text"
                              name="customer[request_details]"
                              placeholder="<?= /* @noEscape */'Comment' ?>"></textarea>
                                    </div>
                                    <div class="fieldset">
                                        <button id="formcallforpricesubmit" type="submit" class="action primary"
                                                title="<?= /* @noEscape */'Request Call For Price' ?>">
                                            <span><span><?= /* @noEscape */ 'Request Call For Price' ?></span></span>
                                        </button>
                                    </div>
                                    <input type="hidden" name="product_id" value="<?php if ($item) {
                                        /* @noEscape */ echo $item->getId();
                                        } ?>"/>

                                    <input type="hidden" name="customer_id" value="<?php if ($customerData) {
                                        /* @noEscape */ echo $customerData->getId();
                                        } ?>"/>
                                    <input type="hidden" name="product_name" value="<?php if ($item) {
                                        /* @noEscape */ echo $item->getName();
                                        } ?>"/>
                                    <p>
                                            <?= 'Note: Please include as much details and relevant options about the
                                            item to help us match your request with an accurate price.' ?>
                                    </p>
                                </div>
                            </form>
                        </div>
                        <script>
                            require(
                                [
                                    'jquery',
                                    'Magento_Ui/js/modal/modal'
                                ],
                                function (
                                    $,
                                    modal
                                ) {
                                    $(document).ready(function () {
                                        var options = {
                                            type: 'popup',
                                            responsive: true,
                                            innerScroll: true,
                                            title: 'Call For Price for <?php if ($item) {
                                                /* @noEscape */ echo $item->getName();
                                                } ?>',
                                            opened: function () {
                                                jQuery(".modal-footer").hide();
                                            },
                                            closeDialog: function () {
                                                this.modal.modal('closeModal');
                                                this.modal = null;
                                            }
                                        };
                                        var popup = modal(options, $('#list-call-for-price-form' +<?=/* @noEscape */
$item->getId()?>))
                                        ;
                                        $("#buttoncallforprice" +<?= /* @noEscape */ $item->getId()?>).on('click',
                                            function () {
                                            $('#list-call-for-price-form' +<?= /* @noEscape */ $item->getId()?>).modal(
                                                "openModal");
                                        });
                                    });
                                });
                        </script>
                                                    <?php endif; ?>
                    <?php endforeach; ?>
                </tr>
                </tbody>
                <tbody>
                <?php foreach ($block->getAttributes() as $attribute):?>
                    <?php $index = 0; ?>
                    <?php if ($block->hasAttributeValueForProducts($attribute)):?>
                         <tr>
                            <?php foreach ($block->getItems() as $item):?>
                                <?php if ($index++ == 0):?>
                                    <th scope="row" class="cell label">
                                        <span class="attribute label">
                                            <?= $block->escapeHtml($attribute->getStoreLabel() ? $attribute->
                                            getStoreLabel() : __($attribute->getFrontendLabel())) ?>
                                        </span>
                                    </th>
                                <?php endif; ?>
                                <td class="cell product attribute">
                                    <div class="attribute value">
                                        <?php switch ($attribute->getAttributeCode()) {
                                            case "price": ?>
                                                <?=
                                                /* @noEscape */ $block->getProductPrice(
                                                    $item,
                                                    '-compare-list-' . $attribute->getCode()
                                                )
                                                ?>
                                                <?php break;
                                            case "small_image": ?>
                                                <?php $block->getImage($item, 'product_small_image')->toHtml();
                                                ?>
                                                <?php break;
                                            default :?>
                                                <?php if (is_string($block->getProductAttributeValue($item, $attribute))
                                                ):?>
                                                    <?= /* @noEscape */ $helper->productAttribute(
                                                        $item,
                                                        $block->getProductAttributeValue($item, $attribute),
                                                        $attribute->getAttributeCode()
                                                    ) ?>
                                                <?php endif; ?>
                                                <?php break;
                                        } ?>
                                    </div>
                                </td>
                            <?php endforeach; ?>
                        </tr>
                    <?php endif; ?>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
        <?php if (!$block->isRedirectToCartEnabled()):?>
            <script type="text/x-magento-init">
            {
                "[data-role=tocart-form]": {
                    "catalogAddToCart": {}
                }
            }
            </script>
        <?php endif; ?>
<?php else:?>
    <div class="message info empty"><div><?= $block->escapeHtml(__('You have no items to compare.')) ?></div>
    </div>
<?php endif; ?>
